name: test_and_lint_stable
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_stable:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.1"
      - run: zig build test

  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.1"
      - run: zig build test
      - run: zig build bootstrap
      - run: zig build test
      - run: zig build
      - run: git diff

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.1"
      - run: zig fmt --check src
